apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: emp-app
  template:
    metadata:
      labels:
        app: emp-app
    spec:
      containers:
      - name: emp-container
        image: aposole0123/employeemanagerapp:6
        ports:
        - containerPort: 80
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: emp-app-service
spec:
  selector:
    app: emp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

